/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        ButtonGroup bg= new ButtonGroup();
        bg.add(malerb);
        bg.add(femalerb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        pwtxt = new javax.swing.JTextField();
        placecb = new javax.swing.JComboBox();
        malerb = new javax.swing.JRadioButton();
        femalerb = new javax.swing.JRadioButton();
        phonetxt = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Register New User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Place");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Phone");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 280, 30));
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 280, 30));
        jPanel1.add(pwtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 280, 30));

        placecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banglore", "Mysore", "Shimoga", "" }));
        jPanel1.add(placecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, 30));

        malerb.setSelected(true);
        malerb.setText("Male");
        jPanel1.add(malerb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        femalerb.setText("Female");
        jPanel1.add(femalerb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 120, -1));
        jPanel1.add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 280, 30));

        submitbtn.setBackground(new java.awt.Color(0, 51, 51));
        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(204, 255, 255));
        submitbtn.setText("Register");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
String name = nametxt.getText().trim();
String email = emailtxt.getText().trim();
String password = pwtxt.getText().trim();
String phone = phonetxt.getText().trim();

if (name.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Name cannot be blank");
}else if (!name.matches("^[a-zA-Z\\s]{2,50}$")) {
    JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces (2-50 characters)");
} else if (email.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Email cannot be blank");
} else if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
    JOptionPane.showMessageDialog(this, "Invalid email format");
} else if (password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password cannot be blank");
} else if (password.length() < 6) {
    JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long");
} else if (phone.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Phone number cannot be blank");
} else if (!phone.matches("\\d{10}")) {
    JOptionPane.showMessageDialog(this, "Phone number must be 10 digits");
} else {
         name=nametxt.getText();
      email=emailtxt.getText();
        password=pwtxt.getText();
       String place=(String)placecb.getSelectedItem();
        String gender="Male";
        if(malerb.isSelected()){
            gender="Male";
        }
        if(femalerb.isSelected()){
            gender="Female";
        }
       phone=phonetxt.getText();
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            App ap=new App();
            String mac=ap.getmac();
            int x=stmt.executeUpdate("insert into user(name,email,password,place,gender,phone,mac) values('"+name+"','"+email+"','"+password+"','"+place+"','"+gender+"','"+phone+"','"+mac+"')");
            if(x!=0){

                JOptionPane.showMessageDialog(this, "Data Added Successfully");
                dispose();
                new Login().setVisible(true);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
                 }
    }//GEN-LAST:event_submitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femalerb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton malerb;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JComboBox placecb;
    private javax.swing.JTextField pwtxt;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
