/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.model.PutObjectRequest;
import java.io.File;
import java.sql.SQLException;
/**
 *
 * @author DELL_PC
 */
public class MainPage extends javax.swing.JFrame {
    private String bucketName = "";// add your bucket name here
      BasicAWSCredentials credentials = new BasicAWSCredentials("", "");// add your access key and secret key here

        public AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(credentials)).withRegion("ap-south-1").build();


    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        ButtonGroup bg=new ButtonGroup();
       
       sessionclass sc=new sessionclass();
        String suser=sc.getusername();
         from.setText(suser);
         System.out.println(suser);
         
           String query = "SELECT email FROM user";

        try (Connection conn = ConnectionManager.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                to.addItem(rs.getString("email"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        message = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        searchemailtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchtable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usemailtxt = new javax.swing.JTextField();
        usearchbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        uemailtxt = new javax.swing.JTextField();
        upwtxt = new javax.swing.JTextField();
        uplacetxt = new javax.swing.JTextField();
        ugendertxt = new javax.swing.JTextField();
        uphonetxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        utable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        messagetxt = new javax.swing.JTextArea();
        sendmessage = new javax.swing.JButton();
        to = new javax.swing.JComboBox();
        sent_message_btn = new javax.swing.JButton();
        received_message_btn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        messagetable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        filetoupload = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        uploadFiletoCloud = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        requestFile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin's Main Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setForeground(new java.awt.Color(0, 0, 204));
        message.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                messageStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("View Users");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 30));

        showbtn.setText("show Data");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });
        jPanel2.add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        showtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(showtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 690, 290));

        message.addTab("Show Users", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Search Users");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 138, 23));

        jLabel12.setText("Enter Email");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));
        jPanel4.add(searchemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 210, -1));

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel4.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        searchtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(searchtable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 700, 100));

        message.addTab("Search User", jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Update Users");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 30));

        jLabel13.setText("Enter email");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 20));
        jPanel3.add(usemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, -1));

        usearchbtn.setText("search");
        usearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usearchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(usearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 80, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 450, 50));

        jLabel14.setText("Name");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel15.setText("email");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel16.setText("password");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel17.setText("place");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel18.setText("gender");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel19.setText("phone");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));
        jPanel3.add(unametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 200, -1));

        uemailtxt.setEditable(false);
        uemailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemailtxtActionPerformed(evt);
            }
        });
        jPanel3.add(uemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 200, -1));
        jPanel3.add(upwtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 200, -1));
        jPanel3.add(uplacetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 200, -1));
        jPanel3.add(ugendertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 200, -1));
        jPanel3.add(uphonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 200, -1));
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 380, 250));

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel3.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));
        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 110, 110));

        utable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(utable);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 690, 80));

        message.addTab("Update Users", jPanel3);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));

        jLabel20.setText("To");

        jLabel21.setText("From");

        from.setEditable(false);
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });

        jLabel22.setText("Message");

        messagetxt.setColumns(20);
        messagetxt.setRows(5);
        jScrollPane5.setViewportView(messagetxt);

        sendmessage.setText("Send Message");
        sendmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessageActionPerformed(evt);
            }
        });

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendmessage)
                .addGap(76, 76, 76))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(from, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(to, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 217, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(26, 26, 26)
                .addComponent(sendmessage)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap(137, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 46, -1, -1));

        sent_message_btn.setText("Sent Messages");
        sent_message_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sent_message_btnActionPerformed(evt);
            }
        });
        jPanel9.add(sent_message_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 307, 255, -1));

        received_message_btn.setText("Received Messages");
        received_message_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                received_message_btnActionPerformed(evt);
            }
        });
        jPanel9.add(received_message_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 307, 289, -1));

        messagetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(messagetable);

        jPanel9.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 348, 730, 100));

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 750, 170));

        jLabel23.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel23.setText("Messages");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 20));

        jPanel8.add(jPanel9);

        message.addTab("Message", jPanel8);

        jPanel16.setBackground(new java.awt.Color(0, 51, 51));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("File to upload");
        jPanel16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 38));
        jPanel16.add(filetoupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 343, 38));

        browse.setBackground(new java.awt.Color(255, 0, 51));
        browse.setText("BROWSE");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        jPanel16.add(browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 123, 36));

        uploadFiletoCloud.setBackground(new java.awt.Color(255, 0, 51));
        uploadFiletoCloud.setText("UPLOAD TO CLOUD");
        uploadFiletoCloud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFiletoCloudActionPerformed(evt);
            }
        });
        jPanel16.add(uploadFiletoCloud, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 151, 36));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 75, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        message.addTab("Upload File", jPanel12);

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("File Name");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 148, 120, 32));
        jPanel14.add(filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 147, 200, 35));

        requestFile.setBackground(new java.awt.Color(255, 0, 0));
        requestFile.setText("Download from cloud");
        requestFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFileActionPerformed(evt);
            }
        });
        jPanel14.add(requestFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 200, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        message.addTab("Download File", jPanel13);

        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 860, 490));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Main Page");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 220, 40));

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void messageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_messageStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_messageStateChanged

    private void requestFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFileActionPerformed
        // TODO add your handling code here:

        String fileName = filename.getText();
        try {
            File outputFile = new File("downloaded_" + fileName);
            s3Client.getObject(new GetObjectRequest(bucketName, fileName), outputFile);
            JOptionPane.showMessageDialog(this, "File downloaded: " + outputFile.getAbsolutePath());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Download failed: " + e.getMessage());
        }
    }//GEN-LAST:event_requestFileActionPerformed

    private void uploadFiletoCloudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFiletoCloudActionPerformed
        // TODO add your handling code here:
        File file = new File(filetoupload.getText());
        try {
            s3Client.putObject(new PutObjectRequest(bucketName, file.getName(), file));
            JOptionPane.showMessageDialog(this, "File uploaded successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Upload failed: " + e.getMessage());
        }
    }//GEN-LAST:event_uploadFiletoCloudActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:

        JFileChooser jc = new JFileChooser(".");

        int ret = jc.showOpenDialog(this);

        if(ret == JFileChooser.APPROVE_OPTION)
        {
            File f  = jc.getSelectedFile();

            String fname = f.getAbsolutePath();

            filetoupload.setText(fname);

        }
    }//GEN-LAST:event_browseActionPerformed

    private void received_message_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_received_message_btnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        sessionclass sc=new sessionclass();
        String user=sc.getusername();
        String sql="select * from message where touser='"+user+"' order by date asc";
        try{
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();
            rst = stmt.executeQuery(sql);
            messagetable.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_received_message_btnActionPerformed

    private void sent_message_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sent_message_btnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        sessionclass sc=new sessionclass();
        String user=sc.getusername();
        String sql="select * from message where fromuser='"+user+"'order by date asc";
        try{
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();
            rst = stmt.executeQuery(sql);
            messagetable.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_sent_message_btnActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_toActionPerformed

    private void sendmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessageActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        Date d=new Date();

        String sql="insert into message values('"+from.getText()+"','"+to.getSelectedItem()+"','"+messagetxt.getText()+"','"+d.toString()+"')";
        try{
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();
            int x = stmt.executeUpdate(sql);
            if(x!=0){
                JOptionPane.showMessageDialog(this, "your message has sent");
            }else{
                JOptionPane.showMessageDialog(this, "message sending failed");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_sendmessageActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();

            String s2=uemailtxt.getText();

            int x=stmt.executeUpdate("delete from user where email='"+s2+"' ");
            if(x!=0){
                JOptionPane.showMessageDialog(this, "Data Deleted");
                unametxt.setText("");
                uemailtxt.setText("");
                upwtxt.setText("");
                uplacetxt.setText("");
                ugendertxt.setText("");
                uphonetxt.setText("");

            }
            rst = stmt.executeQuery("select * from user ");

            utable.setModel(DbUtils.resultSetToTableModel(rst));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            String s1=unametxt.getText();
            String s2=uemailtxt.getText();
            String s3=upwtxt.getText();
            String s4=uplacetxt.getText();
            String s5=ugendertxt.getText();
            String s6=uphonetxt.getText();
            int x=stmt.executeUpdate("update user set name=' "+s1+" ' , password='"+s3+"', place='"+s4+"', gender='"+s5+"', phone='"+s6+"' where email='"+s2+"' ");
            if(x!=0){
                JOptionPane.showMessageDialog(this, "Data Updated");
                unametxt.setText("");
                uemailtxt.setText("");
                upwtxt.setText("");
                uplacetxt.setText("");
                ugendertxt.setText("");
                uphonetxt.setText("");

            }
            rst = stmt.executeQuery("select * from user ");

            utable.setModel(DbUtils.resultSetToTableModel(rst));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void uemailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemailtxtActionPerformed

    private void usearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usearchbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst = stmt.executeQuery("select * from user where email='"+usemailtxt.getText()+"'");
            if(rst.next()){
                unametxt.setText(rst.getString(1));
                uemailtxt.setText(rst.getString(2));
                upwtxt.setText(rst.getString(3));
                uplacetxt.setText(rst.getString(4));
                ugendertxt.setText(rst.getString(5));
                uphonetxt.setText(rst.getString(6));
            }else{

                JOptionPane.showMessageDialog(this, "no Such email exist");
            }
            rst = stmt.executeQuery("select * from user ");

            utable.setModel(DbUtils.resultSetToTableModel(rst));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_usearchbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst = stmt.executeQuery("select * from user where email='"+searchemailtxt.getText()+"'");

            searchtable.setModel(DbUtils.resultSetToTableModel(rst));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst = stmt.executeQuery("select * from user");
            showtable.setModel(DbUtils.resultSetToTableModel(rst));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_showbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField filename;
    private javax.swing.JTextField filetoupload;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane message;
    private javax.swing.JTable messagetable;
    private javax.swing.JTextArea messagetxt;
    private javax.swing.JButton received_message_btn;
    private javax.swing.JButton requestFile;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchemailtxt;
    private javax.swing.JTable searchtable;
    private javax.swing.JButton sendmessage;
    private javax.swing.JButton sent_message_btn;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable showtable;
    private javax.swing.JComboBox to;
    private javax.swing.JTextField uemailtxt;
    private javax.swing.JTextField ugendertxt;
    private javax.swing.JTextField unametxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField uphonetxt;
    private javax.swing.JTextField uplacetxt;
    private javax.swing.JButton uploadFiletoCloud;
    private javax.swing.JTextField upwtxt;
    private javax.swing.JButton usearchbtn;
    private javax.swing.JTextField usemailtxt;
    private javax.swing.JTable utable;
    // End of variables declaration//GEN-END:variables
}
